name: Performance Monitoring

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://timelessaccessories.vercel.app/
            https://timelessaccessories.vercel.app/products
            https://timelessaccessories.vercel.app/categories
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: .github/lighthouse/budget.json

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci
