name: Security Scan

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sundays
  workflow_dispatch: # Allow manual trigger

jobs:
  security:
    name: Security Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

      - name: Run npm audit
        run: npm audit
        continue-on-error: true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Upload security results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
